// expo-env.d.ts is generated by `expo start` and git-ignored, so clean checkouts (CI)
// lack Expo's ambient types — including the `*.css` module declaration for global.css.
/// <reference types="expo/types" />
